project_id = "qdpvgbnkewxrervdoexg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-approval-email]
verify_jwt = true

[functions.admin-expel-user]
verify_jwt = true

[functions.save-consent]
verify_jwt = false

[functions.generate-consent-pdf]
verify_jwt = true
