// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frijspsgcvziucpunrpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyaWpzcHNnY3Z6aXVjcHVucnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzE5NjQsImV4cCI6MjA3Mjg0Nzk2NH0.Fweqjr3E9UQrt9CCBm2EeoBlrpflryRDQoDxWBzK4fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});